.travis.yml - avoid errors due to npm caret versions in node 0.8
A lot of builds are failing in travis like this:

    Error: No compatible version found: blah@'^1.2.0'
    Valid install targets:
    ...

Followed by a list including exactly the version specified.  Huh?
Well, the version of npm installed with nodejs v0.8 doesn't understand
caret versions.  Suggested fix is to upgrade it, as described here:

    https://stackoverflow.com/questions/25902927/travis-not-installing-npm-modules